#!/usr/bin/env bash
set -euo pipefail

# Generated by fallow init --hook-user.
# Installer version: @@FALLOW_INSTALLER_VERSION@@
# Stop hook for Claude Code that runs `fallow audit` after turns
# that edited TS/JS files. Fail-open by design.
#
# Version floor (FALLOW_HOOK_MIN_VERSION, default 2.61.0). Set to empty
# string to disable. Floor comparison uses `sort -V`; GNU and BSD agree
# on plain semver but diverge on prereleases (BSD sorts `2.62.0-alpha.1`
# ABOVE `2.62.0`, GNU below). If you set a prerelease floor explicitly,
# verify the behavior on the target OS. See sibling fallow-gate.sh for
# the same pattern in project-scope (commit gate) form.

if [ "${FALLOW_HOOK_DISABLED:-}" = "1" ]; then exit 0; fi

if ! command -v jq >/dev/null 2>&1; then
  echo "fallow-stop-gate: jq not on PATH, skipping audit." >&2
  exit 0
fi

INPUT="$(cat 2>/dev/null || true)"
if [ -z "$INPUT" ]; then exit 0; fi

SESSION_ID="$(jq -r '.session_id // empty' <<<"$INPUT" 2>/dev/null || true)"
TRANSCRIPT_PATH="$(jq -r '.transcript_path // empty' <<<"$INPUT" 2>/dev/null || true)"
HOOK_CWD="$(jq -r '.cwd // empty' <<<"$INPUT" 2>/dev/null || true)"
STOP_ACTIVE="$(jq -r '.stop_hook_active // false' <<<"$INPUT" 2>/dev/null || echo false)"

if [ "$STOP_ACTIVE" = "true" ]; then exit 0; fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$HOOK_CWD}"
if [ -z "$PROJECT_DIR" ]; then exit 0; fi

debug() { [ "${FALLOW_HOOK_DEBUG:-}" = "1" ] && echo "fallow-stop-gate: $*" >&2; return 0; }

if [ -z "$TRANSCRIPT_PATH" ] || [ ! -r "$TRANSCRIPT_PATH" ]; then
  debug "transcript missing or unreadable, skipping heuristic"
else
  TS_EXTS_RE='\.(ts|tsx|js|jsx|mjs|cjs|mts|cts|svelte|vue|astro)$'
  EXCLUDE_RE='(^|/)(node_modules|\.git|dist|build|target|\.next|\.nuxt|out|coverage)/'
  CHANGED_PATHS="$(tail -n 500 "$TRANSCRIPT_PATH" 2>/dev/null \
    | jq -rR 'fromjson?
             | select(.type=="assistant")
             | .message.content[]?
             | select(.type=="tool_use")
             | select(.name=="Edit" or .name=="Write" or .name=="MultiEdit" or .name=="NotebookEdit")
             | (.input.file_path // .input.notebook_path // empty)' 2>/dev/null \
    | grep -Ei "$TS_EXTS_RE" \
    | grep -Ev "$EXCLUDE_RE" \
    | sort -u || true)"

  if [ -z "$CHANGED_PATHS" ]; then
    debug "no ts/js edits in turn, exiting"
    exit 0
  fi
  debug "ts/js edits detected: $(echo "$CHANGED_PATHS" | wc -l | tr -d ' ') file(s)"
fi

# Project marker detection. Config name list mirrors CONFIG_NAMES in
# crates/config/src/config/parsing.rs — keep in sync if that list changes.
RC_PATH=""
for rc in .fallowrc.json .fallowrc.jsonc fallow.toml .fallow.toml; do
  if [ -f "$PROJECT_DIR/$rc" ]; then RC_PATH="$PROJECT_DIR/$rc"; break; fi
done

if [ -n "$RC_PATH" ]; then
  if [[ "$RC_PATH" == *.json || "$RC_PATH" == *.jsonc ]]; then
    RC_DISABLED="$(jq -r '.hook.disabled // false' "$RC_PATH" 2>/dev/null || echo false)"
    if [ "$RC_DISABLED" = "true" ]; then
      debug "disabled by .fallowrc hook.disabled=true"
      exit 0
    fi
  else
    debug "hook.disabled not parsed for $RC_PATH (MVP: JSON only)"
  fi
fi

if [ -z "$RC_PATH" ] && [ ! -f "$PROJECT_DIR/package.json" ]; then
  debug "no project marker (package.json/.fallowrc absent in $PROJECT_DIR), skipping"
  exit 0
fi
debug "project marker found at $PROJECT_DIR"

if command -v fallow >/dev/null 2>&1; then
  RUNNER=(fallow)
  BIN_DESC="$(command -v fallow)"
elif command -v npx >/dev/null 2>&1 && VER_PROBE="$(npx --no-install fallow --version 2>/dev/null || true)" && [[ "$VER_PROBE" == fallow* ]]; then
  RUNNER=(npx --no-install fallow)
  BIN_DESC="npx --no-install fallow"
else
  echo "fallow-stop-gate: fallow binary not found (tried PATH and npx --no-install), skipping audit." >&2
  exit 0
fi

VERSION_RAW="$("${RUNNER[@]}" --version 2>/dev/null || true)"
VERSION="${VERSION_RAW#fallow }"
VERSION="${VERSION%% *}"

MIN_VERSION="${FALLOW_HOOK_MIN_VERSION-2.61.0}"
if [ -n "$MIN_VERSION" ] && [ -n "$VERSION" ]; then
  LOWER="$(printf '%s\n%s\n' "$MIN_VERSION" "$VERSION" | sort -V | head -n1)"
  if [ "$LOWER" != "$MIN_VERSION" ]; then
    {
      echo "fallow-stop-gate: blocked: $BIN_DESC is fallow $VERSION, below required $MIN_VERSION."
      echo "fallow-stop-gate: upgrade (npm install -g fallow@latest or cargo install fallow-cli),"
      echo "fallow-stop-gate: or set FALLOW_HOOK_MIN_VERSION= to disable."
    } >&2
    exit 2
  fi
fi
debug "binary OK: $BIN_DESC ($VERSION)"

MAX_DIFF="${FALLOW_HOOK_MAX_DIFF-500}"
if command -v git >/dev/null 2>&1 && [ -d "$PROJECT_DIR/.git" ]; then
  TOTAL_COUNT="$(git -C "$PROJECT_DIR" diff --name-only HEAD 2>/dev/null | wc -l | tr -d ' ' || echo 0)"
  if [ "$MAX_DIFF" != "0" ] && [ "$TOTAL_COUNT" -gt "$MAX_DIFF" ]; then
    echo "fallow-stop-gate: diff exceeds $MAX_DIFF files ($TOTAL_COUNT changed), skipping audit." >&2
    exit 0
  fi
  debug "diff size: $TOTAL_COUNT files (threshold $MAX_DIFF)"
fi

# Subsequent phases land below; for now exit 0 (fail-open default).
exit 0
