#!/usr/bin/env bash
set -euo pipefail

# Generated by fallow init --hook-user.
# Installer version: @@FALLOW_INSTALLER_VERSION@@
# Stop hook for Claude Code that runs `fallow audit` after turns
# that edited TS/JS files. Fail-open by design.

if [ "${FALLOW_HOOK_DISABLED:-}" = "1" ]; then exit 0; fi

if ! command -v jq >/dev/null 2>&1; then
  echo "fallow-stop-gate: jq not on PATH, skipping audit." >&2
  exit 0
fi

INPUT="$(cat 2>/dev/null || true)"
if [ -z "$INPUT" ]; then exit 0; fi

SESSION_ID="$(jq -r '.session_id // empty' <<<"$INPUT" 2>/dev/null || true)"
TRANSCRIPT_PATH="$(jq -r '.transcript_path // empty' <<<"$INPUT" 2>/dev/null || true)"
HOOK_CWD="$(jq -r '.cwd // empty' <<<"$INPUT" 2>/dev/null || true)"
STOP_ACTIVE="$(jq -r '.stop_hook_active // false' <<<"$INPUT" 2>/dev/null || echo false)"

if [ "$STOP_ACTIVE" = "true" ]; then exit 0; fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$HOOK_CWD}"
if [ -z "$PROJECT_DIR" ]; then exit 0; fi

debug() { [ "${FALLOW_HOOK_DEBUG:-}" = "1" ] && echo "fallow-stop-gate: $*" >&2; return 0; }

if [ -z "$TRANSCRIPT_PATH" ] || [ ! -r "$TRANSCRIPT_PATH" ]; then
  debug "transcript missing or unreadable, skipping heuristic"
else
  TS_EXTS_RE='\.(ts|tsx|js|jsx|mjs|cjs|mts|cts|svelte|vue|astro)$'
  EXCLUDE_RE='(^|/)(node_modules|\.git|dist|build|target|\.next|\.nuxt|out|coverage)/'
  CHANGED_PATHS="$(tail -n 500 "$TRANSCRIPT_PATH" 2>/dev/null \
    | jq -rR 'fromjson?
             | select(.type=="assistant")
             | .message.content[]?
             | select(.type=="tool_use")
             | select(.name=="Edit" or .name=="Write" or .name=="MultiEdit" or .name=="NotebookEdit")
             | (.input.file_path // .input.notebook_path // empty)' 2>/dev/null \
    | grep -Ei "$TS_EXTS_RE" \
    | grep -Ev "$EXCLUDE_RE" \
    | sort -u || true)"

  if [ -z "$CHANGED_PATHS" ]; then
    debug "no ts/js edits in turn, exiting"
    exit 0
  fi
  debug "ts/js edits detected: $(echo "$CHANGED_PATHS" | wc -l | tr -d ' ') file(s)"
fi

# Subsequent phases land below; for now exit 0 (fail-open default).
exit 0
