#!/usr/bin/env bash
set -euo pipefail

# Generated by fallow init --hook-user.
# Installer version: @@FALLOW_INSTALLER_VERSION@@
# Stop hook for Claude Code that runs `fallow audit` after turns
# that edited TS/JS files. Fail-open by design.

if [ "${FALLOW_HOOK_DISABLED:-}" = "1" ]; then exit 0; fi

if ! command -v jq >/dev/null 2>&1; then
  echo "fallow-stop-gate: jq not on PATH, skipping audit." >&2
  exit 0
fi

INPUT="$(cat 2>/dev/null || true)"
if [ -z "$INPUT" ]; then exit 0; fi

SESSION_ID="$(jq -r '.session_id // empty' <<<"$INPUT" 2>/dev/null || true)"
TRANSCRIPT_PATH="$(jq -r '.transcript_path // empty' <<<"$INPUT" 2>/dev/null || true)"
HOOK_CWD="$(jq -r '.cwd // empty' <<<"$INPUT" 2>/dev/null || true)"
STOP_ACTIVE="$(jq -r '.stop_hook_active // false' <<<"$INPUT" 2>/dev/null || echo false)"

if [ "$STOP_ACTIVE" = "true" ]; then exit 0; fi

PROJECT_DIR="${CLAUDE_PROJECT_DIR:-$HOOK_CWD}"
if [ -z "$PROJECT_DIR" ]; then exit 0; fi

# Subsequent phases land below; for now exit 0 (fail-open default).
exit 0
